name: Download and Process News Entries

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 * * * *'

jobs:
  news:
    name: Download and Process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
         path: ~/.cache/pip
         key: pip-${{ hashFiles('requirements.txt') }}
      - name: Cache Model
        uses: actions/cache@v2
        with:
          path: ${TORCH_HOME}
          key: model
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download
        run: python scripts/download.py
      - name: Process
        run: python scripts/process.py
      - name: Upload Final File to FTP Server
        - name: ssh key with passphrase
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SCP_SERVER }}
            username: ${{ secrets.SCP_USERNAME }}
            key: ${{ secrets.SCP_KEY }}
            passphrase: ${{ secrets.SCP_PASSPHRASE }}
            source: "data/processed/de.json"
            target: "/var/www/opensourc.es/html/__site/Wikunia"