name: Download and Process News Entries

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 * * * *'

jobs:
  news:
    name: Download and Process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
         path: ~/.cache/pip
         key: pip-${{ hashFiles('requirements.txt') }}
      - name: Cache Model
        uses: actions/cache@v2
        with:
          path: ${TORCH_HOME}
          key: model
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download
        run: python scripts/download.py
      - name: Process
        run: python scripts/process.py
      - name: Upload Final File to FTP Server
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "data/processed"
          remoteDir: "www/news"
